sudo: false
dist: trusty
language: node_js
node_js:
  - '6.9'
notifications:
  slack: dartbotapp:3zDEQkGfPGcpoqWaUznJqlht
addons:
  apt:
    packages:
      - google-chrome-stable
before_install:
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
  - npm install
script: 
  - npm run ci
deploy:
   provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN
   local_dir: dist
   fqdn: flightschool.dartbot.com
   on:
     branch: master