sudo: false
dist: trusty
language: node_js
node_js:
  - '8.11'
notifications:
  slack: dartbotapp:3zDEQkGfPGcpoqWaUznJqlht
addons:
  apt:
    packages:
      - google-chrome-stable
before_install:
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
  - npm install
script: 
  - npm run ci
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "flightschool.dartbot.com"
    skip_cleanup: true
    local_dir: dist
    on:
      branch: master