sudo: required
dist: trusty
language: node_js
node_js:
  - '6.9'
notifications:
  slack: dartbotapp:3zDEQkGfPGcpoqWaUznJqlht
addons:
apt:
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
before_script:
  - npm install
script: 
  - npm run ci
deploy:
   provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN
   local_dir: dist
   fqdn: flightschool.dartbot.com
   on:
     branch: master